//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int Id { get; set; }
        public string Institution_Name { get; set; }
        public string Degree_Name { get; set; }
        public System.DateTime Duration_From { get; set; }
        public System.DateTime Duration_TO { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    }
}
