//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experience
    {
        public int Id { get; set; }
        public string Company { get; set; }
        public System.DateTime Duration_From { get; set; }
        public System.DateTime Duration_To { get; set; }
        public string Position { get; set; }
        public string Description { get; set; }
        public string Logo { get; set; }
    }
}
