//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal_info
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Father_Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Field { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public string Nationality { get; set; }
        public string BirthPlace { get; set; }
        public string Description { get; set; }
        public int Projects_done { get; set; }
        public int Projects_online { get; set; }
        public string image { get; set; }
    }
}
